name: Bandit Security Scan and PR Management

on:
  pull_request:
    branches: [ "main" ]

jobs:
  bandit:
    permissions:
      contents: read # for actions/checkout to fetch code
      pull-requests: write # for commenting on and merging PRs

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9" # Use the appropriate Python version for your project

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit Scan
        id: bandit_scan
        run: |
          bandit -r . -f json -o bandit-results.json
          echo "Bandit scan completed."

      - name: Check for Critical or High Vulnerabilities
        id: check_vulns
        run: |
          if grep -q '"issue_severity": "HIGH"' bandit-results.json || grep -q '"issue_severity": "CRITICAL"' bandit-results.json; then
            echo "Critical or High vulnerabilities found. Blocking PR."
            echo "block=true" >> $GITHUB_OUTPUT
          else
            echo "No Critical or High vulnerabilities found. Auto-merging PR."
            echo "block=false" >> $GITHUB_OUTPUT
          fi

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Block PR if Vulnerabilities Found
        if: ${{ steps.check_vulns.outputs.block == 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Critical or High vulnerabilities found. Blocking PR."
          gh pr comment ${{ github.event.pull_request.number }} --body "Block"
          exit 1

      - name: Auto-Merge PR if No Vulnerabilities
        if: ${{ steps.check_vulns.outputs.block == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "No Critical or High vulnerabilities found. Auto-merging PR."
          gh pr merge ${{ github.event.pull_request.number }} --merge --body "Successful"
