name: Bandit

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '40 10 * * 6'

jobs:
  bandit:
    permissions:
      contents: read
      security-events: write
      actions: read

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit
        run: bandit -r . -f json -o results.json

      - name: Check for Critical Vulnerabilities
        id: bandit-check
        run: |
          critical_issues=$(cat results.json | jq '.results[] | select(.issue_severity == "CRITICAL")')
          if [ -n "$critical_issues" ]; then
            echo "::set-output name=block::true"
          else
            echo "::set-output name=block::false"
          fi

      - name: Comment on PR
        uses: actions/github-script@v6
        with:
          script: |
            const block = core.getInput('block');
            if (block === 'true') {
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: 'Block'
              });
              throw new Error('Blocking PR due to critical vulnerabilities');
            } else {
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: 'Successful'
              });
            }

      - name: Merge Pull Request
        if: steps.bandit-check.outputs.block == 'false'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
            });
